use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'BKCloud_Example' do
  pod 'BKCloud', :path => '../'

  target 'BKCloud_Tests' do
    inherit! :search_paths

    
  end
end
